### PR TITLE
Add option to Add or Remove lead tags via shortcode

### PR DESCRIPTION
**Pull request by luizeof**
This PR allow to Add or Remove leads tags using a simple shortcode.

[mautic type="tags" values="mytag,anothertag,-removetag"]

### CODE REVIEW

**Comment by luizeof** [comment]
@escopecz @dbhurley @alanhartless

**Comment by shulard** [comment]
Hello,

I recently entered in the maintainer team on that repo, I'll take a look at your PR quickly to introduce that nice new feature !

**Comment by luizeof** [comment]
I make a few more adjustments to this plugin. I will send each new feature as standalone PR

**Comment by luizeof** [comment]
@shulard  Please ... discard this PR and consider #49 and #50

**Pull request closed without merging**
