### PR TITLE
Refactoring, API connection, Internalization...

### PR DESCRIPTION
**Pull request by robertJurinek**
## Main changes
1. Plugin code is refactored (OOP paradigm).
2. Optionally track only logged-in users.
3. User can choose which data are being tracked by Mautic via CMS. 
4. Internalization (translation ready).
5. API connection which enables updating contacts/leads (inspired by Joomla plugin, this still needs a lot of improvements).

I hope that someone can take over development and extend this code into full-featured, user-friendly plugin for Mautic.

### CODE REVIEW

**Comment by abooster** [comment]
@robertJurinek 
This looks awesome! Question: 
How do I add bbPress **forum role** as a field to be sent to Mautic? 
I have very rudimentary understanding of PHP but I found that this snippet here: 
`$user = new WP_User(get_current_user_id());
echo $user->roles[1];`
always reliably gets the slug of the forum role 
(while `$user->roles[0];` gets the general WP role which I don't need)

So, how do I add **forum role** as a field to be sent to Mautic?

**Comment by abooster** [comment]
@robertJurinek Another question: 
I've heard that OAuth 2 normally needs to be re-authorized every 2 weeks. 
Is that true? Do I need to manually reauthorize it every 2 weeks?
Can't that be done automatically? 
And if not, isn't OAuth 1 a better option?

**Comment by abooster** [comment]
Hmm... for some reason it fails to save Mautic field names for user_login and for display_name.
In Mautic I named the corresponding fields wp_user and wp_alias 
but for some reason the plugin is not saving it. 
It then shows this: 
Warning: Invalid argument supplied for foreach() in /home/XXXXX/public_html/wp-content/plugins/mautic-wordpress-master/classes/WpMauticHelper.php on line 158

**Comment by shulard** [comment]
Hello,

This seems really awesome but at the moment it complicate a lot the plugin structure... I think defining all these changes in one PR is not the way to work here...

Using OOP paradigm seems a very nice idea but relying on namespace (which is a PHP5.3 feature) can break some sites... WordPress is still compatible with PHP5.2...

If you can make smaller PRs to :

* Only track logged in users
* User can choose which data are being tracked by Mautic via CMS
* Implement using OOP
* API connection
* Internationalization

It'll help us to review these changes more easily. I know it's really late since your PR has been submitted... 

With these changes you defined a roadmap for the Mautic plugin, thank you for your work !

**Comment by shulard** [comment]
Hello,

As I said in my previous comment, this PR is to huge to be accepted in one shot.
We have move the codebase forward with unit tests and new features, please take a look at the latest changes !

I'm going to start working on translation after the new WP plugin version will be released.

**Pull request closed without merging**
